FROM jupyterhub/k8s-hub:3.2.1
MAINTAINER Mirko Mariotti <mirko.mariotti@unipg.it>

#USER root

#RUN apt-get update; apt-get install -y --no-install-recommends iproute2

#USER jovyan

RUN pip install --no-cache-dir --upgrade pip oauthenticator

