FROM quay.io/jupyterhub/k8s-hub:3.3.8
MAINTAINER Mirko Mariotti <mirko.mariotti@unipg.it>

#USER root

#RUN apt-get update; apt-get install -y --no-install-recommends iproute2

#USER jovyan
#RUN pip install --upgrade pip
#RUN pip install --no-cache-dir oauthenticator

